language: python

jobs:
  include:
    - name: "Python 3.6.0 on Xenial Linux"
      python: 3.6
    - name: "Python 3.7.0 on Xenial Linux"
      python: 3.7
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8
    - name: "Python 3.6 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
      env: PYTHON_VERSION=3.6.0
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
      env: PYTHON_VERSION=3.7.0
    - name: "Python 3.8 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
      env: PYTHON_VERSION=3.8.0
    - name: "Python 3.6.0 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.0 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.8.0 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  - pip install -r requirements.txt
  - pip install autodocsumm sphinx_rtd_theme jieba
  - |
    pip install -U pip
    pip install --egg --no-binary pyenv pyenv
    export PATH=~/.pyenv/bin:$PATH
    eval "$(pyenv init -)"
    pyenv install --skip-existing $PYTHON_VERSION
    pyenv global $PYTHON_VERSION
    pyenv shell $PYTHON_VERSION
    pip install -U pip setuptools wheel py
    pip install .

env:
  - PYTHONHASHSEED=32 TZ=Asia/Shanghai pytest

script:
  - python setup.py sdist
  - python setup.py bdist_wheel -p any
  - rm -rf build
  - python setup.py bdist_wheel -p manylinux1_x86_64
  - rm -rf build
  - python setup.py bdist_wheel -p win32
  - rm -rf build
  - python setup.py bdist_wheel -p win_amd64
  - rm -rf build
  - sphinx-build doc build/doc

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
  - provider: s3
    access_key_id: $AWS_KEY_ID
    secret_access_key: $AWS_ACCESS_KEY
    bucket: shinnydeploy
    region: ap-east-1
    local_dir: build/doc
    upload-dir: "docs/tqsdk-python/$TRAVIS_BRANCH"
    skip_cleanup: true
    on:
      all_branches: true
  - provider: s3
    access_key_id: $AWS_KEY_ID
    secret_access_key: $AWS_ACCESS_KEY
    bucket: shinnydeploy
    region: ap-east-1
    local_dir: dist
    upload-dir: "dist/tqsdk-python/$TRAVIS_BRANCH"
    skip_cleanup: true
    on:
      all_branches: true
  - provider: pypi
    user: $PYPI_USERNAME
    password: $PYPI_PASSWORD
    skip_cleanup: true
    skip_existing: true
    on:
      tags: true
