name: Python package

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      PYTHONHASHSEED: 32
      TZ: CST-8
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [windows-latest, macOS-latest]
    name: Python ${{ matrix.python-version }} test
    steps:
    - uses: actions/checkout@master
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install autodocsumm sphinx_rtd_theme jieba
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -vv
